export const UPDATE_SPINNER_STATUS = 'GLOBAL_STORE_UPDATE_SPINNER';

export const REFRESH_WHOLE_STORE = 'REFRESH_WHOLE_STORE';

export const GET_BLOCKS_TABLE_DATA = 'GET_BLOCKS_TABLE_DATA';
export const GET_BLOCK_DATA = 'GET_BLOCK_DATA';
export const GET_BLOCK_TRANSACTIONS = 'GET_BLOCK_TRANSACTIONS';
